initFields:
  version: 1.0.0
  devDependencies:
    "@babel/cli": ^7.27.0
    "@babel/core": ^7.26.10
    "@babel/preset-env": ^7.26.9
    "@eslint/js": ^9.24.0
    babel-loader: ^10.0.0
    css-loader: ^7.1.2
    css-minimizer-webpack-plugin: ^7.0.2
    eslint: ^9.24.0
    eslint-config-prettier: ^10.1.1
    eslint-plugin-jest: ^28.11.0
    eslint-plugin-prettier: ^5.2.6
    globals: ^16.0.0
    html-loader: ^5.1.0
    html-webpack-plugin: ^5.6.3
    http-server: ^14.1.1
    jest: ^29.7.0
    mini-css-extract-plugin: ^2.9.2
    prettier: ^3.5.3
    terser-webpack-plugin: ^5.3.14
    webpack: ^5.98.0
    webpack-cli: ^6.0.1
    webpack-dev-server: ^5.2.1
    webpack-merge: ^6.0.1
  homepage: "https://yarnpkg.com"
  license: MIT
  main: index.js
  name: netology-js-adv-br-events
  packageManager: yarn@4.8.1
  scripts:
    build: webpack --config webpack.prod.js
    coverage: jest --coverage
    lint: eslint . --fix
    "preshow:coverage": npm run coverage
    "preshow:dist": npm run build
    "show:coverage": live-server coverage/lcov-report
    "show:dist": http-server dist
    start: webpack serve --config webpack.dev.js
    test: jest

initScope: yarnpkg
